# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 975f0ea95d9a04ced10fbb8761b313d854a1bc5ce62bcff0ede922e6707fdc1dafdaf8d641fb43fa237802fcb427056d339ad75a3311792153562d2f15765f74

test:
  secret_key_base: e21dfb6dc3796182c271f22643404a6c754e5189ce13a5b537fb4d407d6ebdc06cb23abd9c81065257971866583f086f7ee714bfcf0bc1c0c11ddc2b7f943768

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
